### ISSUE TITLE
sopnmf function parameter value missing

### ISSUE THREAD

**Issue by YuYT98** [anbai106/SOPNMF#4]
Dear author,

I have been trying using `sopnmf()` function on a voxel-level based dataset. However, an error occured `TypeError: sopnmf() missing 1 required positional argument: 'participant_tsv_max_memory'`. I tried to find more information regarding this parameter but unfortunately I cannot see more from your instruction. Could you provide an example to show how to set the value for `participant_tsv_max_memory` argument to run the `sopnmf()` function? 

Thank you!

**Comment by anbai106** [comment]
Hi, 

As I explained before, the `participant_tsv_max_memory` is a TSV file that you define manually for the maximum of brain MRI scans that your machine can read into memory in order to initiate the matrices of sopNMF. So it is the same format as the input TSV, but with fewer rows of participants/scans.

Thanks

**Comment by YuYT98** [comment]
Thank you! Could you provide an example for both tsv files to illustrate what they should look like?

**Comment by anbai106** [comment]
The doc has given examples here: https://anbai106.github.io/SOPNMF/
